### ISSUE TITLE
symbol names with hyphens do not colour correctly

### ISSUE THREAD

**Issue by zuriar** [jeluard/prism-clojure#2]
Hi

First, thanks for the clojure highlighting code! I have noticed though that for symbols with hyphens (dashes) there is a problem:

```
(def get-all-tags-in-question [x] .....)
```

here. the first word 'get' and the last word 'question' will be styled but the words 'all' 'tags' 'in' will remain unstyled. However, the dashes will be styled, except for the first dash...

Thanks
Hugh

**Comment by jeluard** [comment]
I haven't used or touched this plugin for ages but if you have some thoughts on how to fix this I am definitively open to a Pull Request!

**Comment by alephyud** [comment]
Had the same issue - submitted a [PR](https://github.com/jeluard/prism-clojure/pull/3) that addresses it.
